### ISSUE TITLE
Results are slightly different when using the local vs. online version of frustratometer

### ISSUE THREAD

**Issue by swarnendut** [proteinphysiologylab/frustratometeR#2]
Using the "1n0r.pdb" file from here.

Results from local version without electrostatics (single residue):
<img width="655" alt="1n0r pdb_singleresidue_local" src="https://user-images.githubusercontent.com/21251867/197632922-7c34fa25-dee3-4213-8431-23fa634774e8.png">

Results from online version without electrostatics (single residue):
<img width="683" alt="1n0r pdb_singleresidue_online" src="https://user-images.githubusercontent.com/21251867/197633185-2cf06a80-afb8-4b7f-b95b-9772f105901d.png">

**Comment by gonzaparra** [comment]
Dear Swarnendut,

The Frustratometer results are never deterministic unless you are using a seed in your code. Let me explain you why. Frustration is a simple comparison between the native energy of your residue or contact and a distribution of energies resulting from generating decoys. 

To generate the decoys in single residue you need to change the amino acid identity, following some background distribution. We do it by sampling identities from the protein you're evaluating itself. We generate 2000 decoys by bootstrapping those identities.

You should observe slightly different results even if you run the algorithm twice either in the server or in your local installation. The important thing is that if you plot one against the other they are all on the diagonal without a clear bias.

I hope I have answered your inquire.

Best, 

Gonzalo

**Comment by swarnendut** [comment]
Dear Gonzalo,

Thank you for the answer. I will see if using a seed I could make the reproducible. I got the explanations and closing this issue.

Best,
Swarnendu
