### ISSUE TITLE
Request for Compatibility of Windows Operating System

### ISSUE THREAD

**Issue by imeMFK01** [proteinphysiologylab/frustratometeR#3]
Dear Dev Team,

May I know whether frustratometeR can be installed on windows 10 or not?

Thanks.

**Comment by gonzaparra** [comment]
Dear imeMFK01,

We haven't developed FrustratometeR to be explicitly compatible with windows neither we have tested it in that operative system. We suggest you to use the docker container to use it in non unix systems. Soon we will make a google collab available.

**Comment by imeMFK01** [comment]
Much appreciated for your kind help.

Thanks.
